# Gems
gems:
   - jekyll-paginate
   - jekyll-gist
   - redcarpet 

# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            ArcQ
tagline:          'code all day, code all night'
description:      ''
url:              https://github.com/ArcQ
baseurl:          /

author:
  name:           'Eddie Law'
  url:            https://www.linkedin.com/in/eddie-law-824b12ba/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/ArcQ/ArcQ.github.io

routes:
  presentations:  remark-presentations
